# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnemonic', models.CharField(max_length=128)),
                ('subject', models.CharField(max_length=128)),
                ('text_content', models.TextField()),
                ('html_content', models.TextField()),
            ],
        ),
    ]
