# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('type', models.IntegerField(choices=[(0, b'how-it-works'), (1, b'battle')], db_index=True)),
                ('title', models.CharField(max_length=128)),
                ('title_en', models.CharField(max_length=128, null=True)),
                ('title_ru', models.CharField(max_length=128, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('image_url', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
